addons:
  apt:
    sources:
    - sourceline: 'ppa:dns-oarc/dnsjit-pr'
    update: true
    packages:
    - autoconf
    - automake
    - dnsjit
language: bash
install: ./autogen.sh
script:
  - ./configure
  - make dist
  - tar zxvf *.tar.gz
  - cd drool-[0-9]*
  - mkdir build
  - cd build
  - ../configure
  - make
  - make test
