language: bash
before_install:
  - sudo add-apt-repository -y ppa:dns-oarc/dnsjit-pr
  - sudo apt-get -qq update
  - sudo apt-get install -y autoconf automake dnsjit
install: ./autogen.sh
script:
  - ./configure
  - make dist
  - tar zxvf *.tar.gz
  - cd drool-[0-9]*
  - mkdir build
  - cd build
  - ../configure
  - make
  - make test
